name: Making Artifact SonarQube Analysis --11

on:
  push:
    branches: [ "main" ]

jobs:
  build-pipe:
    name: compile project
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build + SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_TEST }}
      run: |
        mvn clean verify sonar:sonar \
        -Dsonar.projectKey=java-demo-1 \
        -Dsonar.host.url=http://13.233.144.142:9000 \
        -Dsonar.login=$SONAR_TOKEN

    - uses: actions/upload-artifact@v4
      with:
        name: action-java-sonar-11
        path: target/*.war
