name: Java WAR CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build WAR File
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean package

      - name: Verify WAR Exists
        run: |
          echo "Checking target folder..."
          ls -la target
          if ls target/*.war 1> /dev/null 2>&1; then
            echo "WAR file found ‚úÖ"
          else
            echo "WAR file NOT found ‚ùå"
            exit 1
          fi

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war


  deploy:
    name: Deploy to Tomcat
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./artifact

      - name: Show Downloaded Files
        run: ls -la artifact

      - name: Deploy WAR to Tomcat
        run: |
          WAR_FILE=$(find artifact -name "*.war")
          echo "Deploying $WAR_FILE"

          # Stop Tomcat safely
          /opt/tomcat/bin/shutdown.sh || true
          sleep 5

          # Remove old deployment
          rm -rf /opt/tomcat/webapps/hello-world*
          
          # Copy new WAR
          cp $WAR_FILE /opt/tomcat/webapps/

          # Start Tomcat
          /opt/tomcat/bin/startup.sh
          sleep 5

          echo "Tomcat restarted successfully üöÄ"

      - name: Deployment Success
        run: echo "Deployment Completed Successfully ‚úÖ"
