name: Making Artifact Jar- War-MultiStage-Workflow
on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    name: pre-compile-project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile & Test
        run: |
          mvn compile
          mvn test

  build:
    name: build-project
    runs-on: self-hosted
    needs: compile

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Package Application
        run: |
          mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: action-java-22
          path: target/*.war
